### ISSUE TITLE
NameError: global name 'path' is not defined

### ISSUE THREAD

**Issue by Bha91** [gfanti/Rumor-Spreading#1]
Hi,
Thanks for sharing results and data,
there is little problem in file named "estimation.py" (line 215), I was wondering if you could help.
215  current_vs = path.pop(0)
is this vs_path or it is related to path defined in estimation_spies.py
Thanks

**Comment by gfanti** [comment]
Hi there,

Sorry about that--I've been (very slowly) trying to upgrade this simulation
code to something cleaner. Could you give me some information to help debug?

(1) what OS are you using?
(2) what command did you run prior to getting this bug?
(2) what is your timeline? e.g. If I get this fixed in the next 2 weeks,
would that be soon enough?

Thanks, and apologies for the inconvenience!

Best,
Giulia

**Comment by Bha91** [comment]
Thanks in advance for considering my request, about timeline I plane to get it worked till weekend (Sunday) but don't want to disturb you, I think, I can fix it with some digging in code.
1)I'm using windows 8.1 64 bit with python 2.7.1 32bit, 
2)I just run this code: python realGraphTrials.py --db fb
and the result : (the problem seems compile error no need to run code, IDEs like Pycharm show it as error before run)

('The parameters are:\nDataset = ', 'fb', '\nTrials = ', 1, '\nwrite_results = ', False, '\nalt = ', 0, '\n')
('The parameters are:\nTrials = ', 1, '\nwrite_results = ', False, '\nalt = ', 0, '\n')
('spy probability', 0.0)
----Graph statistics:-----
('the mean degree is', 29.034199999999998)
('num true nodes', 9502)

---

('Trial ', 0, ' / ', 1)
Traceback (most recent call last):
  File "realGraphTrials.py", line 50, in <module>
    diffusion=diffusion, q=q)
  File "C:\Users\Behnam\Desktop\Rumor-Spreading-master\Rumor-Spreading-master\python\runExperiments.py", line 94, in run_dataset
    num_infected, infection_pattern, who_infected, results = infectionModels.inf
ect_nodes_adaptive_diff(source,adjacency,max_time,max_infection)
  File "C:\Users\Behnam\Desktop\Rumor-Spreading-master\Rumor-Spreading-master\python\infectionModels.py", line 560, in infect_nodes_adaptive_diff
    ml_leaf, likelihoods, ml_distance = estimation.max_likelihood(who_infected,virtual_source, adjacency, max_infection, dist_from_source, source)
  File "C:\Users\Behnam\Desktop\Rumor-Spreading-master\Rumor-Spreading-master\python\estimation.py", line 165, in max_likelihood
    likelihoods[i] = compute_graph_likelihood(i, who_infected, adjacency, vs_path, max_infection)
File "C:\Users\Behnam\Desktop\Rumor-Spreading-master\Rumor-Spreading-master\python\estimation.py", line 215, in compute_graph_likelihood
    current_vs = path.pop(0)
NameError: global name 'path' is not defined

**Comment by gfanti** [comment]
Ok great, thanks for the additional information. I'll do my best to fix
this by the weekend. I apologize for the inconvenience, and thank you for
letting me know.

Best,
Giulia

**Comment by gfanti** [comment]
Hi, this issue should be fixed. However, I'm still cleaning up this
codebase (gradually), so please let me know if you run into any more
problems.

**Comment by Bha91** [comment]
Yes it fixed now, Thank you for giving importance and attention to others.
